-- -------------------------------------------------------------
-- SUPABASE SCHEMA MIGRATION: CATEGORIES AND GALLERY TABLES
-- -------------------------------------------------------------
-- INSTRUCTIONS: Copy and execute this SQL script in the 
-- Supabase SQL Editor (https://supabase.com) for your project.

-- 1. Create the categories table
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for categories
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- Categories policies
CREATE POLICY "Allow public read access on categories" ON categories
  FOR SELECT USING (true);

CREATE POLICY "Allow authenticated users all operations on categories" ON categories
  FOR ALL TO authenticated USING (true);

-- Insert seed categories if they do not exist
INSERT INTO categories (name) VALUES 
  ('Seeds'),
  ('Fertilizers'),
  ('Crop Protection'),
  ('Organic Products'),
  ('Sprayers'),
  ('Garden Products')
ON CONFLICT (name) DO NOTHING;


-- 2. Create the gallery table
CREATE TABLE IF NOT EXISTS gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  src TEXT NOT NULL,
  title TEXT NOT NULL,
  desc_text TEXT, -- Named 'desc_text' to avoid SQL keyword 'desc' conflicts
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for gallery
ALTER TABLE gallery ENABLE ROW LEVEL SECURITY;

-- Gallery policies
CREATE POLICY "Allow public read access on gallery" ON gallery
  FOR SELECT USING (true);

CREATE POLICY "Allow authenticated users all operations on gallery" ON gallery
  FOR ALL TO authenticated USING (true);


-- 3. Create the subcategories table
CREATE TABLE IF NOT EXISTS subcategories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category_name TEXT NOT NULL, -- Reference parent category name
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(name, category_name)
);

-- Enable RLS for subcategories
ALTER TABLE subcategories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on subcategories" ON subcategories
  FOR SELECT USING (true);

CREATE POLICY "Allow authenticated users all operations on subcategories" ON subcategories
  FOR ALL TO authenticated USING (true);

-- Add subcategory column to products table
ALTER TABLE products ADD COLUMN IF NOT EXISTS subcategory TEXT;


-- 4. Create the brands table
CREATE TABLE IF NOT EXISTS brands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  category TEXT NOT NULL,
  desc_text TEXT,
  logo_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for brands
ALTER TABLE brands ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on brands" ON brands
  FOR SELECT USING (true);

CREATE POLICY "Allow authenticated users all operations on brands" ON brands
  FOR ALL TO authenticated USING (true);

-- Insert seed brands if they do not exist
INSERT INTO brands (name, category, desc_text, logo_url) VALUES 
  ('IFFCO', 'Fertilizers', 'Indian Farmers Fertiliser Cooperative Limited, a leader in organic and chemical fertilizers.', NULL),
  ('Syngenta', 'Crop Protection', 'Global leader in crop science, providing world-class seeds and pesticides.', NULL),
  ('Bayer Crop Science', 'Crop Protection', 'Pioneers in fungicides, insecticides, and crop yield enhancement solutions.', NULL),
  ('Mahadhan', 'Fertilizers', 'Premium quality specialty fertilizers for fruits, vegetables, and cash crops.', NULL),
  ('Seminis Seeds', 'Seeds', 'High-quality vegetable seed solutions for maximum yield and disease protection.', NULL),
  ('Falcon Garden Tools', 'Garden Products', 'High-grade agriculture and home gardening hand tools and equipment.', NULL)
ON CONFLICT (name) DO NOTHING;
